### PR TITLE
Store the API in a single repository for all clients

### PR DESCRIPTION
**Pull request by jhford**
Right now, the JS client has the ```update-api.js``` script.  This script is used to update all of the api references, but it stores them in Javascript files.  We have a Python client now, and that client uses Node in its build system to translate the Javascript to JSON.  Now we are getting a Go client, and aiui, it's using the Python's client JSON file.

It's great that all of our clients are able to consume these great declarative API references, but let's go the extra step and have a single places where they're all on equal footing!

The alternative approach is to modify references.taskcluster.net to spit out the full apis.json file itself and fetch that from the build system.

I haven't yet modified the client libraries to use this, but for the python client it's just a matter of curling the apis.json file here.  We could also have a 'README.md.fragment' for inclusion in the respective API consumer library's README.md file.

@jonasfj What do you think?

### CODE REVIEW

**Comment by jonasfj** [comment]
The canonical source of API reference definitions is `references.taskcluster.net` this is a public S3 bucket.

The concept of stealing `apis.js`is very bad... Ideally, we should probably just have a single manifest on `references.taskcluster.net` that declares that `Queue` is this reference file... I think we should figure out if we can possibly use hyper json schemas before we invest time in refactoring how references are uploaded to `references.taskcluster.net`... (Granted I don't yet fully understand how links in JSON hyper schemas becomes API methods).

Anyways, both python, node and go have difference calling conventions. So the auto-gen'ed API reference we make in README.md needs to be customized for each of them. IMO the simple thing to do is to just duplicate `update-apis.js` to each client library. It's a pretty simple script... And only the node client needs browserify etc...

I get how duplicating such as script makes us sad... But an extra manual layer of indirection isn't going to make this nicer...
One of the good things about using references.taskcluster.net is that it is an S3 bucket, so if you want to load a reference file dynamically, it's at least somewhat reliable (compared to github).

Honestly, I would rather add a manually updated `references.taskcluster.net/manifest.json` that just makes from API client class name to reference json file. Ie:
```js
{
  "Queue":  "http://references.taskcluster.net/queue/v1/api.json",
  ....
}
```
Then we could reuse that file in future docs or API inspector... who knows.... Granted I'm still tempted to figure out if we want to refactor the whole system in hyper-json schemas.  Either way a tiny manifest file wouldn't scare me.

But I think maintaining such a file on github is a very bad idea. Also the file should only be a mapping to URLs, not the actual JSON like apis.json is. That way the manifest doesn't require changes when a canonical api reference file is update by a component. Besides it's not like client library automation shouldn't fear having to download a few file and stitch them together..

Btw, no we can't reliably update files on S3, the fact that we do it with the canonical api reference files is bad enough... We definitely shouldn't have the components download and add them selves to an apis.json file. I fear eventual inconsistency too much...

**Comment by jonasfj** [comment]
Note, I do think putting a `manifest.json` file on `references.taskcluster.net` would be a good solution to this issue... And that this is a problem worth addressing.  Even if we later move to hyper json schema....

The `manifest.json` is rarely updated and could also live in the client libraries... which is what it effectively does for the node.js client, though here it lives as part of the `apis.json`.

**Comment by jhford** [comment]
Given that all libraries need a manifest.json file and the content ought to be the same for all, can we store it on references.tc.net?

What's the best way to do that?

**Comment by jhford** [comment]
I'm going to send an email and delete this repo

**Pull request closed without merging**
